### ISSUE TITLE
createSurfaceProvider() is no longer in PreviewView class.

### ISSUE THREAD

**Issue by vikrant-shah27** [AyusmaTech/CameraRectCropSample#3]
createSurfaceProvider() is no longer in PreviewView class. is there any alternative way to achieve a similar kind of functionality without using createSurfaceProvider()

Where did you find non-final PreviewView Class with createSurfaceProvider()??

**Comment by AyusmaTech** [comment]
Hello, you can use viewFinder.surfaceProvider or viewFinder.getSurfaceProvider for. Java
